package PSG.backEnd.model.enums.treasury;

import java.math.BigDecimal;

/**
 * Types of movements applicable to a {@link PSG.backEnd.model.entity.treasury.CashBox}.
 * The {@link #sign()} value is multiplied by the (always positive) movement amount to
 * obtain the signed delta applied to the cash box balance.
 */
public enum CashBoxMovementType {
    INCREMENTO_MANUAL(1),       // manual top-up (+)
    DECREMENTO_MANUAL(-1),      // manual withdrawal (−)
    AJUSTE(0),                  // adjustment — sign is computed from delta, not from this enum
    PAGO_EMITIDO(-1),           // outflow generated by a CashPayment (−)
    TRANSFERENCIA_INTERNA(0);   // future use — sign defined by the operation

    private final int sign;

    CashBoxMovementType(int sign) {
        this.sign = sign;
    }

    public int sign() {
        return sign;
    }

    public BigDecimal applySign(BigDecimal amount) {
        if (sign == 0 || amount == null) return amount;
        return sign > 0 ? amount : amount.negate();
    }
}
